### ISSUE TITLE
terminal error

### ISSUE THREAD

**Issue by achyuth2016** [herrbischoff/awesome-osx-command-line#113]
Last login: Wed Jun 22 10:27:53 on ttys004
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin15/rbconfig.rb:213: warning: Insecure world writable dir /usr/local in PATH, mode 040757
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin15/rbconfig.rb:213: warning: Insecure world writable dir /usr/local in PATH, mode 040757
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin15/rbconfig.rb:213: warning: Insecure world writable dir /usr/local in PATH, mode 040757

**Comment by 00101010b** [comment]
`sudo chmod o-w -R /usr/local`

**Comment by herrbischoff** [comment]
What exactly do you need help with? Please do not just paste an error message without explaining what you wanted to achieve. I'm going to close this. Please feel free to open another issue with details about what you tried to do, what you already tried but what did not work and what you cannot figure out.
