### ISSUE TITLE
Backup interval changing doesn't work

### ISSUE THREAD

**Issue by bmalynovytch** [herrbischoff/awesome-osx-command-line#116]
Command line to change default backup interval doesn't work with OS X El Capitan 10.11.5:
https://github.com/herrbischoff/awesome-osx-command-line/blame/master/README.md#L267

`Launch Daemons` was renamed in `LaunchDaemons`, but even when changing the path, there's still an error.

**Comment by herrbischoff** [comment]
Thanks for reporting this I'm going to investigate further. If anyone has insight into this, I'll be happy to hear it.

Could you please also post the error message you get?

**Comment by bmalynovytch** [comment]
```
> sudo defaults write /System/Library/LaunchDaemons/com.apple.backupd-auto StartInterval -int 1800
2016-06-29 17:59:26.832 defaults[21885:5499044] Could not write domain /System/Library/LaunchDaemons/com.apple.backupd-auto; exiting
```

**Comment by herrbischoff** [comment]
Thanks. Hmm... My first instinct would be to blame [SIP](https://github.com/herrbischoff/awesome-osx-command-line#system-integrity-protection). Would you be willing to disable it, run the command and enable it again afterward to see if that may work?

**Comment by bmalynovytch** [comment]
You're welcome.
I won't have much time to reboot my MBP as I have tones of work opened.
I'll keep you informed if I get any chance to give it a try.

**Comment by herrbischoff** [comment]
I see, don't we all? ;) No haste, I'm looking forward to hearing from you.

**Comment by herrbischoff** [comment]
@bmalynovytch: Any luck?

**Comment by bmalynovytch** [comment]
Sorry no, had no time to give it a try :/

**Comment by herrbischoff** [comment]
Alright, I'm closing the issue now.

**Comment by k0ala** [comment]
I had the same issue in El Capitan. Disabling SIP as per your link solved the problem, thanks.
