### ISSUE TITLE
Password generation command fails if locale set to 

### ISSUE THREAD

**Issue by greyhoundforty** [herrbischoff/awesome-osx-command-line#122]
From this discussion on [StackExchange](http://unix.stackexchange.com/questions/45404/why-cant-tr-read-from-dev-urandom-on-osx): 

"Your tr attempts to interpret its input as text in UTF-8 encoding. So it will complain and abort upon the first byte sequence which is not valid UTF-8"

```
❯ tr -dc A-Za-z0-9_ < /dev/urandom | head -c 20 | pbcopy
tr: Illegal byte sequence

~
❯ LC_CTYPE=C tr -dc A-Za-z0-9_ < /dev/urandom | head -c 20 | pbcopy

~
❯ pbpaste
PscPJMkpKa2Nzxn9GpHZ
```

**Comment by herrbischoff** [comment]
This indeed appears to be so, are you on Sierra? It worked without a hitch on El Capitan.

**Comment by greyhoundforty** [comment]
I am indeed on Sierra.

**Comment by herrbischoff** [comment]
Well, something must have changed since then. I'm using an identical shell setup and this happens for me too. I will add a note to the entry and research this further.

**Comment by greyhoundforty** [comment]
Thanks!

**Comment by herrbischoff** [comment]
According to the manpage of `tr`:

> The LANG, LC_ALL, LC_CTYPE and LC_COLLATE environment variables affect the execution of tr as described in environ(7).

As `tr` requires text files, if any charmap is set, it will have problems with a stream of binary data, as coming from `/dev/urandom`.

The correct command should therefore probably be:

```bash
LC_ALL=C tr -dc "[:alpha:][:alnum:]" < /dev/urandom | head -c 20 | pbcopy
```
