### ISSUE TITLE
mas

### ISSUE THREAD

**Issue by dkhamsing** [herrbischoff/awesome-osx-command-line#125]
https://github.com/mas-cli/mas

what do you think?

**Comment by dkhamsing** [comment]
Oops, should go here.. https://github.com/herrbischoff/awesome-command-line-apps 
But anyway, same question

**Comment by herrbischoff** [comment]
This is nice! I especially value that it is not made in Node.js like 90%+ of the command line tools of the last couple of years appear to be. Feel free to add a PR to Awesome Command Line Apps. 👍
