### ISSUE TITLE
zsh is located under /bin/zsh

### ISSUE THREAD

**Issue by m99coder** [herrbischoff/awesome-osx-command-line#138]
Related to section https://github.com/herrbischoff/awesome-osx-command-line#zsh I wonder if only my version of `zsh` (using it together with `ohmyzsh`) is located under `/bin/zsh` or if it’s really a mistake.

**Comment by herrbischoff** [comment]
macOS comes with Zsh, albeit an older one. If you did not use Homebrew, MacPorts or the like to install it, that's where you'd find it.

**Comment by m99coder** [comment]
You are right. Sorry. I installed `zsh` now by using `Homebrew`. It’s now located under `/usr/local/bin/zsh`.

**Comment by herrbischoff** [comment]
No problem. :)
