### ISSUE TITLE
SF Mono is available without Xcode

### ISSUE THREAD

**Issue by mikew** [herrbischoff/awesome-osx-command-line#141]
They're bundled with Terminal.app, in `/Applications/Utilities/Terminal.app/Contents/Resources/Fonts`

**Comment by tobiasboyd** [comment]
They are also in the (non-beta) Xcode package, so `cp -v /Applications/Xcode.app/Contents/SharedFrameworks/DVTKit.framework/Versions/A/Resources/Fonts/SFMono-* ~/Library/Fonts` works fine for me with Xcode 8.2.1 on El Cap.

**Comment by herrbischoff** [comment]
Good catch, both of you. I think I'm going to go with the Terminal.app variant as it does not require anything to be installed at all. The current entry was added at a time when the typeface was exclusively used in Xcode (and the then-beta version).
