### ISSUE TITLE
Stop Contacts from Automatically Linking

### ISSUE THREAD

**Issue by bkarlan** [herrbischoff/awesome-osx-command-line#174]
Please excuse me if this is the wrong location to ask this question but I have looked everywhere and this is the only place that I think might have an answer. I'm looking for some kind of terminal command to stop contacts in Sierra from auto linking to what it thinks is a similar contact.   I just want to turn off the automatic linking function. I want a contact in one account to display as its own contact even if it has the same name as another contact in a different account.

**Comment by herrbischoff** [comment]
I don't believe this is possible. I suggest sending your feedback to Apple: https://www.apple.com/feedback/

As this is unlikely to be solved, I'm closing this.
