### ISSUE TITLE
Show Wi-Fi Network Passwords command giving error

### ISSUE THREAD

**Issue by rileyjshaw** [herrbischoff/awesome-osx-command-line#24]
From [Show Wi-Fi Network Passwords](https://github.com/herrbischoff/awesome-osx-command-line#show-wi-fi-network-passwords), running:

```
security find-generic-password -ga "ROUTERNAME" | grep "password:"
```

produces the following error on my machine (latest OSX):

```
security: SecKeychainSearchCopyNext: The specified item could not be found in the keychain.
```

**Comment by herrbischoff** [comment]
Of course you need to exchange "ROUTERNAME" with the SSID of the router you wish to query the password from. ;)
