### ISSUE TITLE
Add mac dev-setup repo? https://github.com/donnemartin/dev-setup

### ISSUE THREAD

**Issue by donnemartin** [herrbischoff/awesome-osx-command-line#26]
Awesome repo!  Curious if you think it might be a good idea to add the following mac dev setup focused repo as a link?  The repo has a good amount of Mac shell commands and tools.

https://github.com/donnemartin/dev-setup

If so, I suppose it would probably have to go under a new section?

If there's interest I can submit a pull request.  Thanks!

**Comment by herrbischoff** [comment]
Thanks! Looks like an interesting repository. However, there's a little too much stuff thrown together for my taste though.

**Comment by donnemartin** [comment]
Np, closing.
