### ISSUE TITLE
Text-only list of commands for direct usage

### ISSUE THREAD

**Issue by herrbischoff** [herrbischoff/awesome-osx-command-line#35]
I just wondered about creating a subfolder in this repo with several additional files:

- A setup script, containing sane default settings for OS X
- An alias file containing useful command snippets and shortcuts to be sourced
- Separate alias files for functions and shortcuts for specific applications (as to give a home to solutions like #23) and environments

The idea is obviously influenced by [Mathias Bynens' repo](https://github.com/mathiasbynens/dotfiles/blob/master/.osx) but I'd like to go beyond it, creating a structured collection of settings, aliases and shortcuts. Kind of like commented master config files for OS X. For Unix tools that need a config file, often there is a sample file with comments, explaining the settings. That's what I have in mind.

What do you think?

**Comment by vinkla** [comment]
Would also be good if we could run tests on the snippets. Maybe using Travis?

**Comment by herrbischoff** [comment]
@vinkla: Interesting idea. Travis does support Mac OS as a testing target. However, writing effective tests for simple configuration changes could prove to be challenging, as there is usually no output.

**Comment by vinkla** [comment]
We could just create a script that is executed and see how it performs on different systems. Take a look at this repository: https://github.com/mikemcquaid/strap

**Comment by herrbischoff** [comment]
I see, so what you have in mind is a simple (global) check instead of adding tests for every snippet separately. ;)

**Comment by vinkla** [comment]
Yeah, that will make it easier to implement :)

**Comment by herrbischoff** [comment]
Alright. I will see if I find the time to work on the new content today. I'll leave the creation of the `.travis.yml` file to you. :) If you like, I'm going to add you as a collaborator when things are added and set up. This way you can trigger Travis builds at will.

**Comment by vinkla** [comment]
Aaah, cool! Let me know when I can start :)

**Comment by herrbischoff** [comment]
Alright, @vinkla: as of now you have push access to the repository. Use it wisely! ;)

I have set up a new branch `setup-files` for us to work with. I believe the structure should be self-explanatory. I use Vim as my main code editor so the files are tailored to this environment. To spare yourself and others the pain of having to adjust editor settings manually, there is also an `.editorconfig` file. Which should (given the correct plugin for your code editor is installed) adjust the code formatting automatically.

I believe the files should ultimately be in a separate folder which contains its own `README.md` with basic information about their intent and instructions on how to use them.

Let's see what we can create! I'm especially interested in how the Travis tests will run. They are set to run only when a `.travis.yml` file is present. So as soon as you add one, it's go time.

**Comment by vinkla** [comment]
Alright! I'll get started directly :)

**Comment by herrbischoff** [comment]
Closing this ticket because for now we're sticking to the main list.
