### ISSUE TITLE
Deleting preference files is unreliable

### ISSUE THREAD

**Issue by perryclarke** [herrbischoff/awesome-osx-command-line#40]
In the "Remove Apple Remote Desktop Settings" entry (https://github.com/herrbischoff/awesome-osx-command-line#remove-apple-remote-desktop-settings) preferences are removed by "rm"ing the preference files which doesn't work reliably because of the way preferences are cached.  The correct way to remove prefs is using `defaults delete`.

**Comment by herrbischoff** [comment]
Thanks for the suggestion. Would you mind creating a pull request for it?

**Comment by herrbischoff** [comment]
Fixed through #45.
