### ISSUE TITLE
Travis integration

### ISSUE THREAD

**Issue by herrbischoff** [herrbischoff/awesome-osx-command-line#43]
Create a `.travis.yml` file that runs test on all included bash scripts along with the alias and function files.

**Comment by G07cha** [comment]
@herrbischoff what about pull request validation? For correct style and script? I can write some code for style check btw.

**Comment by herrbischoff** [comment]
@G07cha: That would indeed be nice. You can send a PR to the `travis` branch so @vinkla, you and I can take a look. Thanks!

**Comment by herrbischoff** [comment]
Closing this due to #102.
