### ISSUE TITLE
El Capitan Mission Control Desktop Previews

### ISSUE THREAD

**Issue by rad182** [herrbischoff/awesome-osx-command-line#65]
Hi. Does anyone knows how to enable this? show desktop previews right away without hovering the mouse at the top/desktops? TIA

**Comment by darlanmendonca** [comment]
I'd love if there was this feature

**Comment by ryanshuck** [comment]
Kind of a hack, but you can set your top left hot corner to launch Mission Control, and your mouse is already up there.

**Comment by herrbischoff** [comment]
As there have been no answers in over a year, I'm going to close this issue.
