### ISSUE TITLE
Disk Utility repairPermissions gone in 10.11

### ISSUE THREAD

**Issue by keith** [herrbischoff/awesome-osx-command-line#8]
Not sure how you're handling adding/removing stuff based on new OS X releases. But with 10.11 [this](https://github.com/herrbischoff/awesome-osx-command-line#repair-file-permissions) no longer works. See [here](https://support.apple.com/en-us/HT201560) for details.

**Comment by herrbischoff** [comment]
Thanks for the pointer! I verified this and indeed the commands for `verifyPermissions` and `repairPermissions` are gone. I will update the main file accordingly.

**Comment by herrbischoff** [comment]
Done.

**Comment by keith** [comment]
Thanks!


--
Keith Smiley
