### ISSUE TITLE
Turning off mDNSResponder fails with error

### ISSUE THREAD

**Issue by ryanshuck** [herrbischoff/awesome-osx-command-line#94]
sudo defaults write /System/Library/LaunchDaemons/com.apple.mDNSResponder ProgramArguments -array-add "-NoMulticastAdvertisements"
Fails with: defaults[379:4885] Could not write domain /System/Library/LaunchDaemons/com.apple.mDNSResponder; exiting

**Comment by herrbischoff** [comment]
Ahh… This may very well be another instance of System Integrity Protection at work. You probably use El Capitan, correct?

**Comment by ryanshuck** [comment]
I do indeed. I think the rest of the ones I did all worked fine.

**Comment by herrbischoff** [comment]
Please see issue #39. Apparently adding `.plist` to the domain name does work.

**Comment by ryanshuck** [comment]
Definitely doesn't work, even after running csrutil disable. I read the guy's post, but I can't replicate it.

**Comment by ryanshuck** [comment]
After a little more work, I found a repeatable process.

In recovery, run 
`csrutil disable && reboot`
Once back in OS X, log in as an admin user and run 
`sudo launchctl unload /System/Library/LaunchDaemons/com.apple.mDNSResponder.plist`
'sudo defaults write /System/Library/LaunchDaemons/com.apple.mDNSResponder.plist ProgramArguments -array-add "-NoMulticastAdvertisements"'
`sudo launchctl load /System/Library/LaunchDaemons/com.apple.mDNSResponder.plist`
Reboot and go back into recovery and run
`csrutil enable && reboot`

That worked for me.
